from typing import Dict, List, Any
from app.rbac import permissions as p
from app.rbac.scopes import ScopeType

# 5 Core Departments
DEPARTMENTS = [
    "Supervision",
    "Assessment / Audit",
    "Security",
    "Operations",
    "CSE Administrator"
]

# 13 Authoritative Roles and their specifications
ROLE_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    # Supervision
    "Supervision Authority": {
        "department": "Supervision",
        "scope": ScopeType.ENTERPRISE,
        "description": "Oversees sectoral and cross-entity cyber supervision, final decisions, and directives.",
        "permissions": [
            p.CSE_READ,
            p.INVESTIGATIONS_READ,
            p.EVIDENCE_READ,
            p.FINDING_READ,
            p.FINDING_REVIEW,
            p.FINDING_APPROVE,
            p.FINDING_REJECT,
            p.ASSESSMENT_READ,
            p.RISK_READ,
            p.REMEDIATION_READ,
            p.SUPERVISION_READ,
            p.SUPERVISION_CREATE,
            p.SUPERVISION_ASSIGN,
            p.SUPERVISION_REVIEW,
            p.SUPERVISION_DECIDE,
            p.SUPERVISION_APPROVE,
            p.SUPERVISION_CLOSE,
            p.SUPERVISION_ESCALATE,
            p.SUPERVISORY_CASE_READ,
            p.SUPERVISORY_CASE_CREATE,
            p.SUPERVISORY_CASE_UPDATE,
            p.SUPERVISORY_CASE_ASSIGN,
            p.SUPERVISORY_CASE_REVIEW,
            p.SUPERVISORY_CASE_CLOSE,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.ESCALATION_ASSIGN,
            p.ESCALATION_RESOLVE,
            p.ESCALATION_CLOSE,
            p.SUPERVISORY_DECISION_READ,
            p.SUPERVISORY_DECISION_CREATE,
            p.SUPERVISORY_DECISION_APPROVE,
            p.SUPERVISORY_DECISION_CLOSE,
            p.SUPERVISION_DECISIONS,
            p.AUDIT_LOGS_READ,
            p.ANALYTICS_READ,
            p.ANALYTICS_RUN,
            p.DATASET_READ,
            p.DATASETS_READ,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_REVIEW,
            p.NEGATIVE_SPACE_VALIDATE,
            p.NEGATIVE_SPACE_DISMISS,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.NEGATIVE_SPACE_SIGNAL_REVIEW,
            p.NEGATIVE_SPACE_SIGNAL_VALIDATE,
            p.NEGATIVE_SPACE_SIGNAL_DISMISS,
            p.EXECUTIVE_CISO_READ,
            p.EXECUTIVE_MANAGEMENT_READ,
            p.EXECUTIVE_EXPORT,
        ]
    },
    "Supervision Analyst": {
        "department": "Supervision",
        "scope": ScopeType.SECTOR,
        "description": "Analyzes sectoral cyber security events, assessment reports, and trends.",
        "permissions": [
            p.CSE_READ,
            p.INVESTIGATIONS_READ,
            p.EVIDENCE_READ,
            p.FINDING_READ,
            p.FINDING_CREATE,
            p.FINDING_UPDATE,
            p.FINDING_SUBMIT,
            p.FINDING_REVIEW,
            p.ASSESSMENT_READ,
            p.RISK_READ,
            p.REMEDIATION_READ,
            p.SUPERVISION_READ,
            p.SUPERVISION_REVIEW,
            p.SUPERVISION_RECOMMEND,
            p.SUPERVISION_ESCALATE,
            p.SUPERVISORY_CASE_READ,
            p.SUPERVISORY_CASE_CREATE,
            p.SUPERVISORY_CASE_UPDATE,
            p.SUPERVISORY_CASE_REVIEW,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.SUPERVISORY_DECISION_READ,
            p.DATASET_READ,
            p.DATASET_CREATE,
            p.DATASET_UPLOAD,
            p.DATASET_VALIDATE,
            p.DATASET_IMPORT,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.ANALYTICS_RUN,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_CREATE,
            p.NEGATIVE_SPACE_RUN,
            p.NEGATIVE_SPACE_REVIEW,
            p.NEGATIVE_SPACE_VALIDATE,
            p.NEGATIVE_SPACE_DISMISS,
            p.NEGATIVE_SPACE_CONVERT_FINDING,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.NEGATIVE_SPACE_SIGNAL_REVIEW,
            p.NEGATIVE_SPACE_SIGNAL_VALIDATE,
            p.NEGATIVE_SPACE_SIGNAL_DISMISS,
        ]
    },
    "Sector Security Authority": {
        "department": "Supervision",
        "scope": ScopeType.SECTOR,
        "description": "Sector-level cyber oversight, incident monitoring, and risk aggregation.",
        "permissions": [
            p.CSE_READ,
            p.INVESTIGATIONS_READ,
            p.FINDING_READ,
            p.ASSESSMENT_READ,
            p.RISK_READ,
            p.REMEDIATION_READ,
            p.SUPERVISION_READ,
            p.SUPERVISION_REVIEW,
            p.SUPERVISION_RECOMMEND,
            p.SUPERVISION_ESCALATE,
            p.SUPERVISORY_CASE_READ,
            p.SUPERVISORY_CASE_REVIEW,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.SUPERVISORY_DECISION_READ,
            p.ANALYTICS_READ,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.EXECUTIVE_CISO_READ,
            p.EXECUTIVE_MANAGEMENT_READ,
            p.EXECUTIVE_EXPORT,
        ]
    },

    # Assessment / Audit
    "Authorized Assessor": {
        "department": "Assessment / Audit",
        "scope": ScopeType.ORGANIZATION,
        "description": "Conducts security assessments, evaluates controls, uploads evidence, and draft findings.",
        "permissions": [
            p.ASSESSMENT_READ,
            p.ASSESSMENT_CREATE,
            p.ASSESSMENT_UPDATE,
            p.ASSESSMENT_ASSIGN,
            p.ASSESSMENT_SUBMIT,
            p.ASSESSMENT_CONTROLS_READ,
            p.ASSESSMENT_CONTROLS_UPDATE,
            p.EVIDENCE_READ,
            p.EVIDENCE_CREATE,
            p.FINDING_READ,
            p.FINDING_CREATE,
            p.FINDING_UPDATE,
            p.FINDING_SUBMIT,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.DATASET_READ,
            p.DATASET_CREATE,
            p.DATASET_UPLOAD,
            p.DATASET_VALIDATE,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_CREATE,
            p.NEGATIVE_SPACE_RUN,
            p.NEGATIVE_SPACE_REVIEW,
            p.NEGATIVE_SPACE_VALIDATE,
            p.NEGATIVE_SPACE_DISMISS,
            p.NEGATIVE_SPACE_CONVERT_FINDING,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.NEGATIVE_SPACE_SIGNAL_REVIEW,
            p.NEGATIVE_SPACE_SIGNAL_VALIDATE,
            p.NEGATIVE_SPACE_SIGNAL_DISMISS,
        ]
    },
    "Auditor Reviewer": {
        "department": "Assessment / Audit",
        "scope": ScopeType.ORGANIZATION,
        "description": "Independently reviews and approves assessment submissions and audit findings.",
        "permissions": [
            p.ASSESSMENT_READ,
            p.ASSESSMENT_REVIEW,
            p.ASSESSMENT_APPROVE,
            p.ASSESSMENT_REJECT,
            p.ASSESSMENT_CLOSE,
            p.ASSESSMENT_CONTROLS_READ,
            p.FINDING_READ,
            p.FINDING_REVIEW,
            p.FINDING_APPROVE,
            p.FINDING_REJECT,
            p.EVIDENCE_READ,
            p.EVIDENCE_VERIFY,
            p.REMEDIATION_READ,
            p.REMEDIATION_VALIDATE,
            p.REMEDIATION_VERIFY,
            p.REMEDIATION_EVIDENCE_READ,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.AUDIT_LOGS_READ,
            p.DATASET_READ,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.NOTIFICATIONS_READ,
        ]
    },

    # Security
    "CISO": {
        "department": "Security",
        "scope": ScopeType.ENTERPRISE,
        "description": "Enterprise cyber security executive with high-level oversight and decision visibility.",
        "permissions": [
            p.ALERTS_READ,
            p.CSE_READ,
            p.INVESTIGATIONS_READ,
            p.EVIDENCE_READ,
            p.FINDING_READ,
            p.ASSESSMENT_READ,
            p.RISK_READ,
            p.RISK_UPDATE,
            p.RISK_ASSESS,
            p.RISK_TREAT,
            p.RISK_ACCEPT,
            p.RISK_CLOSE,
            p.RISK_REVIEW,
            p.RISK_APPROVE,
            p.RISK_EXCEPTION_READ,
            p.RISK_EXCEPTION_REVIEW,
            p.RISK_EXCEPTION_APPROVE,
            p.RISK_EXCEPTION_CLOSE,
            p.RISK_TREATMENT_READ,
            p.RISK_TREATMENT_REVIEW,
            p.RISK_TREATMENT,
            p.RISK_EXCEPTIONS,
            p.REMEDIATION_READ,
            p.REMEDIATION_CREATE,
            p.REMEDIATION_UPDATE,
            p.REMEDIATION_ASSIGN,
            p.REMEDIATION_VALIDATE,
            p.REMEDIATION_VERIFY,
            p.REMEDIATION_CLOSE,
            p.REMEDIATION_EVIDENCE_READ,
            p.REMEDIATION_EVIDENCE_VERIFY,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.AUDIT_LOGS_READ,
            p.ANALYTICS_READ,
            p.DATASETS_READ,
            p.SYSTEM_STATUS_READ,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.SUPERVISION_READ,
            p.SUPERVISORY_CASE_READ,
            p.EXECUTIVE_CISO_READ,
            p.EXECUTIVE_MANAGEMENT_READ,
            p.EXECUTIVE_EXPORT,
        ]
    },
    "GRC/Risk Officer": {
        "department": "Security",
        "scope": ScopeType.ORGANIZATION,
        "description": "Manages enterprise risk registers, treatments, exceptions, and control compliance.",
        "permissions": [
            p.RISK_READ,
            p.RISK_CREATE,
            p.RISK_UPDATE,
            p.RISK_ASSIGN,
            p.RISK_ASSESS,
            p.RISK_TREAT,
            p.RISK_ACCEPT,
            p.RISK_CLOSE,
            p.RISK_REVIEW,
            p.RISK_APPROVE,
            p.RISK_EXCEPTION_READ,
            p.RISK_EXCEPTION_CREATE,
            p.RISK_EXCEPTION_REVIEW,
            p.RISK_EXCEPTION_APPROVE,
            p.RISK_EXCEPTION_CLOSE,
            p.RISK_TREATMENT_READ,
            p.RISK_TREATMENT_CREATE,
            p.RISK_TREATMENT_UPDATE,
            p.RISK_TREATMENT_REVIEW,
            p.RISK_TREATMENT,
            p.RISK_EXCEPTIONS,
            p.FINDING_READ,
            p.FINDING_CREATE,
            p.CONTROL_READ,
            p.CONTROL_UPDATE,
            p.ASSESSMENT_READ,
            p.ASSESSMENT_CONTROLS_READ,
            p.REMEDIATION_READ,
            p.REMEDIATION_CREATE,
            p.REMEDIATION_UPDATE,
            p.REMEDIATION_ASSIGN,
            p.REMEDIATION_VALIDATE,
            p.REMEDIATION_VERIFY,
            p.REMEDIATION_CLOSE,
            p.REMEDIATION_EVIDENCE_READ,
            p.REMEDIATION_EVIDENCE_VERIFY,
            p.REMEDIATION_EVIDENCE_REJECT,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.AUDIT_LOGS_READ,
            p.DATASET_READ,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.NOTIFICATIONS_READ,
        ]
    },
    "Senior Management": {
        "department": "Security",
        "scope": ScopeType.ENTERPRISE,
        "description": "Executive leadership with strategic dashboard and read-only overview.",
        "permissions": [
            p.CSE_READ,
            p.FINDING_READ,
            p.ASSESSMENT_READ,
            p.RISK_READ,
            p.REMEDIATION_READ,
            p.ANALYTICS_READ,
            p.SYSTEM_STATUS_READ,
            p.NOTIFICATIONS_READ,
            p.SUPERVISION_READ,
            p.SUPERVISORY_CASE_READ,
            p.NEGATIVE_SPACE_READ,
            p.EXECUTIVE_MANAGEMENT_READ,
            p.EXECUTIVE_EXPORT,
        ]
    },

    # Operations
    "IT Infrastructure Team": {
        "department": "Operations",
        "scope": ScopeType.ORGANIZATION,
        "description": "Maintains infrastructure security controls and implements technical remediations.",
        "permissions": [
            p.CONTROL_READ,
            p.REMEDIATION_READ,
            p.REMEDIATION_UPDATE,
            p.REMEDIATION_START,
            p.REMEDIATION_BLOCK,
            p.REMEDIATION_SUBMIT_EVIDENCE,
            p.REMEDIATION_EVIDENCE_READ,
            p.REMEDIATION_EVIDENCE_CREATE,
            p.REMEDIATION_EVIDENCE,
            p.SYSTEM_STATUS_READ,
            p.NOTIFICATIONS_READ,
        ]
    },
    "Remediation Owner": {
        "department": "Operations",
        "scope": ScopeType.ASSIGNED,
        "description": "Responsible for executing assigned remediation tasks and uploading validation evidence.",
        "permissions": [
            p.REMEDIATION_READ,
            p.REMEDIATION_UPDATE,
            p.REMEDIATION_START,
            p.REMEDIATION_BLOCK,
            p.REMEDIATION_SUBMIT_EVIDENCE,
            p.REMEDIATION_EVIDENCE_READ,
            p.REMEDIATION_EVIDENCE_CREATE,
            p.REMEDIATION_EVIDENCE,
            p.ASSIGNMENTS_READ,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.NOTIFICATIONS_READ,
        ]
    },
    "SOC Analyst": {
        "department": "Operations",
        "scope": ScopeType.ORGANIZATION,
        "description": "Monitors alerts, triggers CSEs, conducts investigations, and escalates incidents.",
        "permissions": [
            p.ALERTS_READ,
            p.ALERTS_MANAGE,
            p.CSE_READ,
            p.CSE_CREATE,
            p.CSE_UPDATE,
            p.CSE_ESCALATE,
            p.INVESTIGATIONS_READ,
            p.INVESTIGATIONS_CREATE,
            p.INVESTIGATIONS_UPDATE,
            p.EVIDENCE_READ,
            p.EVIDENCE_CREATE,
            p.FINDING_READ,
            p.FINDING_CREATE,
            p.FINDING_UPDATE,
            p.FINDING_SUBMIT,
            p.ESCALATION_READ,
            p.ESCALATION_CREATE,
            p.DATASET_READ,
            p.DATASET_CREATE,
            p.DATASET_UPDATE,
            p.DATASET_UPLOAD,
            p.DATASET_VALIDATE,
            p.DATASET_IMPORT,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.ANALYTICS_RUN,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_REVIEW,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.NEGATIVE_SPACE_SIGNAL_REVIEW,
        ]
    },
    "Control Owner": {
        "department": "Operations",
        "scope": ScopeType.ORGANIZATION,
        "description": "Maintains and monitors implementation of specific security controls.",
        "permissions": [
            p.CONTROL_READ,
            p.CONTROL_UPDATE,
            p.ASSESSMENT_CONTROLS_READ,
            p.ASSESSMENT_CONTROLS_UPDATE,
            p.REMEDIATION_READ,
            p.NOTIFICATIONS_READ,
        ]
    },

    # Platform Administration
    "CSE Administrator": {
        "department": "CSE Administrator",
        "scope": ScopeType.ENTERPRISE,
        "description": "Manages identity, users, roles, organizations, and platform configuration.",
        "permissions": [
            p.USERS_MANAGE,
            p.USERS_READ,
            p.ROLES_MANAGE,
            p.ROLES_READ,
            p.PERMISSIONS_MANAGE,
            p.PERMISSIONS_READ,
            p.DEPARTMENTS_MANAGE,
            p.DEPARTMENTS_READ,
            p.ORGANIZATIONS_MANAGE,
            p.ORGANIZATIONS_READ,
            p.SECTORS_MANAGE,
            p.SECTORS_READ,
            p.ACCESS_REQUESTS_MANAGE,
            p.ACCESS_REQUESTS_READ,
            p.SYSTEM_SETTINGS_MANAGE,
            p.SYSTEM_STATUS_READ,
            p.AUDIT_LOGS_READ,
            p.ALERTS_READ,
            p.ALERTS_MANAGE,
            p.CSE_READ,
            p.CSE_CREATE,
            p.CSE_UPDATE,
            p.CSE_ASSIGN,
            p.CSE_ESCALATE,
            p.CSE_CLOSE,
            p.INVESTIGATIONS_READ,
            p.INVESTIGATIONS_CREATE,
            p.INVESTIGATIONS_UPDATE,
            p.EVIDENCE_READ,
            p.EVIDENCE_CREATE,
            p.FINDING_READ,
            p.FINDING_CREATE,
            p.FINDING_UPDATE,
            p.FINDING_SUBMIT,
            p.FINDING_REVIEW,
            p.FINDING_APPROVE,
            p.FINDING_REJECT,
            p.FINDING_CLOSE,
            p.ASSESSMENT_READ,
            p.ASSESSMENT_CREATE,
            p.ASSESSMENT_UPDATE,
            p.ASSESSMENT_ASSIGN,
            p.ASSESSMENT_SUBMIT,
            p.ASSESSMENT_REVIEW,
            p.ASSESSMENT_APPROVE,
            p.ASSESSMENT_REJECT,
            p.ASSESSMENT_CLOSE,
            p.ASSESSMENT_CONTROLS_READ,
            p.ASSESSMENT_CONTROLS_UPDATE,
            p.EVIDENCE_VERIFY,
            p.RISK_READ,
            p.RISK_CREATE,
            p.RISK_UPDATE,
            p.RISK_ASSIGN,
            p.RISK_ASSESS,
            p.RISK_TREAT,
            p.RISK_ACCEPT,
            p.RISK_CLOSE,
            p.RISK_REVIEW,
            p.RISK_APPROVE,
            p.RISK_EXCEPTION_READ,
            p.RISK_EXCEPTION_CREATE,
            p.RISK_EXCEPTION_REVIEW,
            p.RISK_EXCEPTION_APPROVE,
            p.RISK_EXCEPTION_CLOSE,
            p.RISK_TREATMENT_READ,
            p.RISK_TREATMENT_CREATE,
            p.RISK_TREATMENT_UPDATE,
            p.RISK_TREATMENT_REVIEW,
            p.REMEDIATION_READ,
            p.REMEDIATION_CREATE,
            p.REMEDIATION_UPDATE,
            p.REMEDIATION_ASSIGN,
            p.REMEDIATION_START,
            p.REMEDIATION_BLOCK,
            p.REMEDIATION_SUBMIT_EVIDENCE,
            p.REMEDIATION_VALIDATE,
            p.REMEDIATION_VERIFY,
            p.REMEDIATION_CLOSE,
            p.REMEDIATION_EVIDENCE_READ,
            p.REMEDIATION_EVIDENCE_CREATE,
            p.REMEDIATION_EVIDENCE_VERIFY,
            p.REMEDIATION_EVIDENCE_REJECT,
            p.DATASET_READ,
            p.DATASET_CREATE,
            p.DATASET_UPDATE,
            p.DATASET_UPLOAD,
            p.DATASET_VALIDATE,
            p.DATASET_IMPORT,
            p.DATASET_DELETE,
            p.DATASETS_READ,
            p.ANALYTICS_READ,
            p.ANALYTICS_RUN,
            p.NOTIFICATIONS_READ,
            p.NEGATIVE_SPACE_READ,
            p.NEGATIVE_SPACE_CREATE,
            p.NEGATIVE_SPACE_RUN,
            p.NEGATIVE_SPACE_REVIEW,
            p.NEGATIVE_SPACE_VALIDATE,
            p.NEGATIVE_SPACE_DISMISS,
            p.NEGATIVE_SPACE_CONVERT_FINDING,
            p.NEGATIVE_SPACE_SIGNAL_READ,
            p.NEGATIVE_SPACE_SIGNAL_REVIEW,
            p.NEGATIVE_SPACE_SIGNAL_VALIDATE,
            p.NEGATIVE_SPACE_SIGNAL_DISMISS,
        ]
    }
}

# Attach Step 16 permissions across roles
for r in ROLE_DEFINITIONS.values():
    if p.MY_WORK_READ not in r["permissions"]:
        r["permissions"].append(p.MY_WORK_READ)

for r_name in ["Supervision Authority", "Auditor Reviewer", "CSE Administrator", "CISO", "Senior Management"]:
    if r_name in ROLE_DEFINITIONS and p.AUDIT_LOGS_EXPORT not in ROLE_DEFINITIONS[r_name]["permissions"]:
        ROLE_DEFINITIONS[r_name]["permissions"].append(p.AUDIT_LOGS_EXPORT)

