class NotificationTypes:
    ASSIGNMENT = "ASSIGNMENT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    ESCALATION = "ESCALATION"
    VALIDATION_REQUIRED = "VALIDATION_REQUIRED"
    OVERDUE = "OVERDUE"
    CRITICAL_RISK = "CRITICAL_RISK"
    CRITICAL_FINDING = "CRITICAL_FINDING"
    NEGATIVE_SPACE_SIGNAL = "NEGATIVE_SPACE_SIGNAL"
    IMPORT_COMPLETE = "IMPORT_COMPLETE"
    IMPORT_FAILED = "IMPORT_FAILED"
    SUPERVISORY_DECISION = "SUPERVISORY_DECISION"
    SYSTEM = "SYSTEM"


class NotificationPriorities:
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
