"""add_scope_type_to_roles

Revision ID: 9c300d76f9c2
Revises: ef18ee0824e5
Create Date: 2026-09-13 11:11:39.497892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c300d76f9c2'
down_revision: Union[str, Sequence[str], None] = 'ef18ee0824e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('scope_type', sa.String(), server_default='organization', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'scope_type')
    # ### end Alembic commands ###
